# Generated by Django 5.0.1 on 2025-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fullName', models.CharField(max_length=150)),
                ('studentId', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
